name: Python CI

on:
    schedule:
        # each fifteen day of month
        - cron: "0 0 15 * *"
    push:
        branches:
            - main
        paths:
            - "python/**"
            - ".github/workflows/python.yml"
    pull_request:
        branches:
            - main
        paths:
            - "python/**"
            - ".github/workflows/python.yml"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v6
              with:
                  version: "latest"

            - name: all tests except the expected failing one
              working-directory: python
              run: uv run pytest -k "not test_order_cannot_be_updated_or_canceled_if_paid" -v

            - name: expected failing test
              working-directory: python
              run: |
                  ! uv run pytest -k "test_order_cannot_be_updated_or_canceled_if_paid" --tb=short
